### ISSUE TITLE
更新版本后启动图修改失效

### ISSUE THREAD

**Issue by internetWei** [iversonxh/DynamicLaunchImage#1]
我测试的过程中发现，我在1.0版本修改了启动图。当我更新至1.1时我上次修改的启动图会失效。

**Comment by gengcong1991** [comment]
是不是图片的存取路径存的是全路径？如果是这样的，只需要改为半路径就行了，每次安装沙盒后面的都会变化

**Comment by internetWei** [comment]
不是你说的意思，当APP更新版本后系统会重新生成一套启动图，这样的话1.0版本替换的启动图就会失效。

**Comment by gengcong1991** [comment]
哦 那估计是App Store为了减少启动图缓存对新版本的影响，springboard中检查版本变化了又特殊配置吧，结合这个点，之前apple在官网回复说启动图缓存对线上包不会有影响就说的通了，升级了就再处理一遍呗也好解决的；

**Comment by internetWei** [comment]
你还是没Get到我的点。
例如我作为用户，下载了你的APP的1.0版本，然后我修改了启动图，为方便理解假设图片名称为图1。
现在APP版本更新到了1.1版本，我从App Store下载了最新版本1.1。现在我打开APP应该要显示我在1.0版本设置的图1对吧，但是我现在打开APP显示的默认启动图而不是我上次修改的启动图。
不知道我这样解释你是否明白。
至于你说的再处理一遍。怎么处理？让用户每次升级版本后再按照同一套逻辑设置一遍启动图吗？这明显是框架本身的问题吧。

**Comment by gengcong1991** [comment]
不好意思刚看到消息了，我很清楚你的问题，不就是升级app之后系统把这个框架中原来缓存的图片给清理了，导致用户设置的自定义启动图失效了呗。我上面不是说了吗，系统在新app安装的时候会自动清理springboard，框架修改启动图也是利用这个原理把图片写到这里了，系统清理了他有什么办法？解决办法不也很简单吗？担心系统清理了，那你就把用户设置的启动图自己再储存一份，每次版本号发生变化或者当你检查到本地的springboard里面的启动图被清理了，就拿自己存储的那份再用这个框架提供的方法设置一遍自定义启动图不就行了，多简单的事说了这么多你都不明白怎么做的开发？难道框架作者能什么场景都考虑得到吗？白嫖习惯了什么都不想自己动脑子解决，怪不得iOS开发整体氛围不行呢，呵呵了。人家作者只是提供一个修改启动图的思路，难道能把你的所有业务场景都考虑的清清楚楚，没脑子的白嫖党！

**Comment by gengcong1991** [comment]
> 你还是没Get到我的点。
> 例如我作为用户，下载了你的APP的1.0版本，然后我修改了启动图，为方便理解假设图片名称为图1。
> 现在APP版本更新到了1.1版本，我从App Store下载了最新版本1.1。现在我打开APP应该要显示我在1.0版本设置的图1对吧，但是我现在打开APP显示的默认启动图而不是我上次修改的启动图。
> 不知道我这样解释你是否明白。
> 至于你说的再处理一遍。怎么处理？让用户每次升级版本后再按照同一套逻辑设置一遍启动图吗？这明显是框架本身的问题吧。

不好意思刚看到消息了，我很清楚你的问题，不就是升级app之后系统把这个框架中原来缓存的图片给清理了，导致用户设置的自定义启动图失效了呗。我上面不是说了吗，系统在新app安装的时候会自动清理springboard，框架修改启动图也是利用这个原理把图片写到这里了，系统清理了他有什么办法？解决办法不也很简单吗？担心系统清理了，那你就把用户设置的启动图自己再储存一份，每次版本号发生变化或者当你检查到本地的springboard里面的启动图被清理了，就拿自己存储的那份再用这个框架提供的方法设置一遍自定义启动图不就行了，多简单的事说了这么多你都不明白怎么做的开发？难道框架作者能什么场景都考虑得到吗？白嫖习惯了什么都不想自己动脑子解决，怪不得iOS开发整体氛围不行呢，呵呵了。人家作者只是提供一个修改启动图的思路，难道能把你的所有业务场景都考虑的清清楚楚，没脑子的白嫖党！
